# Generated by Django 5.1.6 on 2025-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="industry_type",
            field=models.CharField(max_length=100),
        ),
    ]
